### PR TITLE
SSR compatibility

### LINKED ISSUE #2: pageData type is (not) optional
Hello,

LSP is giving me squiggly lines for `pageData`:

```
Property 'pageData' is missing in type '{ url: URL; routeId: string | null; }' but required in type '{ relPathToRoutes?: string | undefined; routeId: string | null; url: URL; crumbs?: Crumb[] | undefined; titleSanitizer?: ((title: string) => string) | undefined; routeModules?: Record<string, ModuleData> | undefined; pageData: any; }'. ​ts(2741)
```

Generated type file is like this:
```js
declare const __propDef: {
	props: {
		relPathToRoutes?: string | undefined;
		routeId: string | null;
		url: URL;
		crumbs?: Crumb[] | undefined;
		titleSanitizer?: ((title: string) => string) | undefined;
		routeModules?: Record<string, ModuleData> | undefined;
		pageData: any;
	};
	events: {
		[evt: string]: CustomEvent<any>;
	};
	slots: {
		default: {
			crumbs: Crumb[];
			routeModules: Record<string, ModuleData> | undefined;
		};
	};
};
```

We probably need this in the svelte component:

```
export let pageData: any | undefined = undefined;
```

I can send a PR if you like.

### PR DESCRIPTION
**Pull request by basaran**
Hi, could you review this please? My issues were related to SSR I believe.

P.S I also took the time to touch a few other places and added a prettier config.

closes #2

### CODE REVIEW

**Comment by diericx** [comment]
Could you provide some context for these changes? How did you identify that SSR is causing issues? Can you provide a method for reproducing these errors? I am not seeing any issues.

**Comment by basaran** [comment]
the actual project I had many moving parts, so I wasn't able to completely reproduce the issue. Please check to see if you have received an invite to access the base starter I built myself. On that base starter, you should still be able to see the HMR stops working when you add the breadcrumbs.

I am thinking it doesn't completely break on the starter, because the project is small and there are not too many components to import and things don't go completely out of sync.

**Comment by basaran** [comment]
As for the changes, we are basically wrapping the component within a the `browser` provided by sveltekit. Other changes I made were to add types to some functions and fix what appeared to be a broken type import.

**Comment by diericx** [comment]
I didn't realize this component was breaking HMR, that is a good call out. That is easily reproducible and even shows up when running the project in repo. Maybe we should isolate this discussion and PR to fixing that. I'll start investigating that today.

This project was developed for use in another larger SvelteKit project which you can find here:
https://github.com/diericx/climbing_notebook/

It works well and I haven't noticed any other issues, certainly no catastrophic issues such as the ones you are seeing. If you can create a minimal reproduction repo for any other issues I'm more than happy to investigate.

**Comment by basaran** [comment]
sure thing, let's close this one then. I will send an atomic PR just for the SSR.

**Comment by diericx** [comment]
After looking into this I think it has something to do with the path in the glob import. I think it works using a relative path: `"./src/"` instead of `"/src/"`. Let me know if that works for you as well... don't know why this breaks stuff though

**Pull request closed without merging**
